spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: candidate
    password: java
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO

app:
  blacklist:
    - admin
    - administrator
    - root
---
spring:
  profiles: test
app:
  blacklist:
    - admin
    - administrator
    - root