spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username: candidate
    password: java
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
app:
  blacklist:
    - admin
    - administrator
    - root
---
spring:
  profiles: test
app:
  blacklist:
    - admin
    - administrator
    - root
---
spring:
  profiles: container
  datasource:
    url: jdbc:postgresql://db:5432/interview